kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app.label }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.port }}
